spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/study01 #최초 웹콘솔에서 jdbc url:jdbc:h2:~/study01 한 번 수행하고 로그아웃 후 왼쪽 url 입력 후 시작
    username: sa
    password:
    driver-class-name: org.h2.Driver

token:
  expiration_time: 360000
  secret: token_user_service_asdf123$#%

encryption-test: '{cipher}107d55eae379a8a6c6741598bd40cab4cfbe4e72979aaf625e8df8cd8329cf4069e0794ebfc85fd6028062b257872f30'

gateway:
  ip: 127.0.0.1

