spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/study01 #최초 웹콘솔에서 jdbc url:jdbc:h2:~/study01 한 번 수행하고 로그아웃 후 왼쪽 url 입력 후 시작
    username: sa
    password:
    driver-class-name: org.h2.Driver

token:
  expiration_time: 360000
  secret: token_user_service_asdf123$#%

gateway:
  ip: 127.0.0.1

