spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/study01 #최초 웹콘솔에서 jdbc url:jdbc:h2:~/study01 한 번 수행하고 로그아웃 후 왼쪽 url 입력 후 시작
    username: sa
    password:
    driver-class-name: org.h2.Driver

token:
  expiration_time: 360000
  secret: token_user_service_asdf123$#%

encryption-test: '{cipher}AQACMY5uvdKAY6nzocUd+7QRl15J9MdE08rCNUwehQMlPylF0uXlJWNjS3MwZswhXy1HArgesd7ZOQ5r4Mic0FLOgJphqveIYKWcZRSoFBbP8sw8e9GeszWD/nBHph3xXae1Q+QmeTDgueKqukTAplf+Sp38wWWLE/bdaEvLGj8e+CPRvy1ShbOjV9DGKHEAyfTcuVjFjdRdfIboi92FRmidxD34vafHZKNnqocwpgOny2f7Bq80vlZzjHT9/iFbKexox6kciI1O22rpv5dmnfABtCZ8QS2o5CgiNDfOnOWW36ZgRcXEsJIb5PxSG7dmz6JKUqXDmMMWVTUuwsjWbzU0rQp2WR4MlYM6wwcIrjH2ZhCU8fxz8qGQf26BpTC9R1k='

gateway:
  ip: 127.0.0.1

order_service:
  url: http://order-service/order-service/%s/orders
  exception:
    orders_is_empty: Sorry, User's order is empty.



